/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as LeistungenRouteImport } from './routes/leistungen'
import { Route as ProjektKalkulierenRouteImport } from './routes/projekt-kalkulieren'
import { Route as ProjekteRouteImport } from './routes/projekte'
import { Route as UeberUnsRouteImport } from './routes/ueber-uns'
import { Route as LeistungenSlugRouteImport } from './routes/leistungen_.$slug'
import { Route as ProjekteSlugRouteImport } from './routes/projekte_.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenRoute = LeistungenRouteImport.update({
  id: '/leistungen',
  path: '/leistungen',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjektKalkulierenRoute = ProjektKalkulierenRouteImport.update({
  id: '/projekt-kalkulieren',
  path: '/projekt-kalkulieren',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjekteRoute = ProjekteRouteImport.update({
  id: '/projekte',
  path: '/projekte',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberUnsRoute = UeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenSlugRoute = LeistungenSlugRouteImport.update({
  id: '/leistungen_/$slug',
  path: '/leistungen/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjekteSlugRoute = ProjekteSlugRouteImport.update({
  id: '/projekte_/$slug',
  path: '/projekte/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/projekt-kalkulieren': typeof ProjektKalkulierenRoute
  '/projekte': typeof ProjekteRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/leistungen/$slug': typeof LeistungenSlugRoute
  '/projekte/$slug': typeof ProjekteSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/projekt-kalkulieren': typeof ProjektKalkulierenRoute
  '/projekte': typeof ProjekteRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/leistungen/$slug': typeof LeistungenSlugRoute
  '/projekte/$slug': typeof ProjekteSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/projekt-kalkulieren': typeof ProjektKalkulierenRoute
  '/projekte': typeof ProjekteRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/leistungen_/$slug': typeof LeistungenSlugRoute
  '/projekte_/$slug': typeof ProjekteSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/leistungen'
    | '/projekt-kalkulieren'
    | '/projekte'
    | '/ueber-uns'
    | '/leistungen/$slug'
    | '/projekte/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/leistungen'
    | '/projekt-kalkulieren'
    | '/projekte'
    | '/ueber-uns'
    | '/leistungen/$slug'
    | '/projekte/$slug'
  id:
    | '__root__'
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/leistungen'
    | '/projekt-kalkulieren'
    | '/projekte'
    | '/ueber-uns'
    | '/leistungen_/$slug'
    | '/projekte_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  LeistungenRoute: typeof LeistungenRoute
  ProjektKalkulierenRoute: typeof ProjektKalkulierenRoute
  ProjekteRoute: typeof ProjekteRoute
  UeberUnsRoute: typeof UeberUnsRoute
  LeistungenSlugRoute: typeof LeistungenSlugRoute
  ProjekteSlugRoute: typeof ProjekteSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen': {
      id: '/leistungen'
      path: '/leistungen'
      fullPath: '/leistungen'
      preLoaderRoute: typeof LeistungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekt-kalkulieren': {
      id: '/projekt-kalkulieren'
      path: '/projekt-kalkulieren'
      fullPath: '/projekt-kalkulieren'
      preLoaderRoute: typeof ProjektKalkulierenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekte': {
      id: '/projekte'
      path: '/projekte'
      fullPath: '/projekte'
      preLoaderRoute: typeof ProjekteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber-uns': {
      id: '/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof UeberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen_/$slug': {
      id: '/leistungen_/$slug'
      path: '/leistungen/$slug'
      fullPath: '/leistungen/$slug'
      preLoaderRoute: typeof LeistungenSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekte_/$slug': {
      id: '/projekte_/$slug'
      path: '/projekte/$slug'
      fullPath: '/projekte/$slug'
      preLoaderRoute: typeof ProjekteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  LeistungenRoute: LeistungenRoute,
  ProjektKalkulierenRoute: ProjektKalkulierenRoute,
  ProjekteRoute: ProjekteRoute,
  UeberUnsRoute: UeberUnsRoute,
  LeistungenSlugRoute: LeistungenSlugRoute,
  ProjekteSlugRoute: ProjekteSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
